package badsmells;

/*
 * Refactored smell: Divergent Change
 *
 * What changed:
 * - Extracted reporting, SQL, and CSV responsibilities into separate classes
 *
 * Why better:
 * Each class now changes for one reason only. Report formatting, persistence,
 * and export logic can evolve independently with less risk.
 */
public class DivergentChangeExample {

    static class StudentReportFormatter {
        private final String reportTitle;
        private final String reportFooter;

        StudentReportFormatter(String reportTitle, String reportFooter) {
            this.reportTitle = reportTitle;
            this.reportFooter = reportFooter;
        }

        public String formatStudentReport(String name, int score) {
            return reportTitle + "\n" + name + ": " + score + "\n" + reportFooter;
        }
    }

    static class ExamResultSqlBuilder {
        private final String tableName;
        private final String databaseUrl;

        ExamResultSqlBuilder(String tableName, String databaseUrl) {
            this.tableName = tableName;
            this.databaseUrl = databaseUrl;
        }

        public String buildSqlInsert(String name, int score) {
            return "/* " + databaseUrl + " */ INSERT INTO " + tableName
                    + "(name, score) VALUES ('" + name + "', " + score + ")";
        }
    }

    static class CsvExporter {
        private final String separator;
        private final boolean includeHeader;

        CsvExporter(String separator, boolean includeHeader) {
            this.separator = separator;
            this.includeHeader = includeHeader;
        }

        public String export(String name, int score) {
            String csvRow = name + separator + score;
            return includeHeader ? "name" + separator + "score\n" + csvRow : csvRow;
        }
    }

    public void clientCode() {
        StudentReportFormatter formatter =
                new StudentReportFormatter("Exam Results", "Generated by registrar office");
        ExamResultSqlBuilder sqlBuilder =
                new ExamResultSqlBuilder("exam_results", "jdbc:mysql://localhost:3306/school");
        CsvExporter csvExporter = new CsvExporter(",", true);

        System.out.println(formatter.formatStudentReport("Nino", 95));
        System.out.println(sqlBuilder.buildSqlInsert("Nino", 95));
        System.out.println(csvExporter.export("Nino", 95));
    }
}
